package com.mtjin.cnunoticeapp.utils.constants

const val EXTRA_NOTICE_SAVE = "EXTRA_NOTICE_SAVE"
const val EXTRA_NOTICE_DELETE = "EXTRA_NOTICE_DELETE"
const val EXTRA_NOTICE_LINK = "EXTRA_NOTICE_LINK"
const val EXTRA_BOARD_NAME = "EXTRA_BOARD_NAME"
const val TAG_DIALOG_EVENT = "TAG_ADD_DIALOG_EVENT"